export interface FakerLanguage {
  code: string;
  name: string;
}
interface FakerMethods {
  [key: string]: string[];
}
export const languages = ():FakerLanguage[] => [
  { code: 'af_ZA', name: 'Afrikaans (South Africa)' },
  { code: 'ar', name: 'Arabic' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'base', name: 'Base' },
  { code: 'cs_CZ', name: 'Czech (Czechia)' },
  { code: 'da', name: 'Danish' },
  { code: 'de', name: 'German' },
  { code: 'de_AT', name: 'German (Austria)' },
  { code: 'de_CH', name: 'German (Switzerland)' },
  { code: 'dv', name: 'Maldivian' },
  { code: 'el', name: 'Greek' },
  { code: 'en', name: 'English' },
  { code: 'en_AU', name: 'English (Australia)' },
  { code: 'en_AU_ocker', name: 'English (Australia Ocker)' },
  { code: 'en_BORK', name: 'English (Bork)' },
  { code: 'en_CA', name: 'English (Canada)' },
  { code: 'en_GB', name: 'English (Great Britain)' },
  { code: 'en_GH', name: 'English (Ghana)' },
  { code: 'en_HK', name: 'English (Hong Kong)' },
  { code: 'en_IE', name: 'English (Ireland)' },
  { code: 'en_IN', name: 'English (India)' },
  { code: 'en_NG', name: 'English (Nigeria)' },
  { code: 'en_US', name: 'English (United States)' },
  { code: 'en_ZA', name: 'English (South Africa)' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'es', name: 'Spanish' },
  { code: 'es_MX', name: 'Spanish (Mexico)' },
  { code: 'fa', name: 'Farsi/Persian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fr', name: 'French' },
  { code: 'fr_BE', name: 'French (Belgium)' },
  { code: 'fr_CA', name: 'French (Canada)' },
  { code: 'fr_CH', name: 'French (Switzerland)' },
  { code: 'fr_LU', name: 'French (Luxembourg)' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hr', name: 'Croatian' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'id_ID', name: 'Indonesian (Indonesia)' },
  { code: 'it', name: 'Italian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ka_GE', name: 'Georgian (Georgia)' },
  { code: 'ko', name: 'Korean' },
  { code: 'lv', name: 'Latvian' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'nb_NO', name: 'Norwegian (Norway)' },
  { code: 'ne', name: 'Nepali' },
  { code: 'nl', name: 'Dutch' },
  { code: 'nl_BE', name: 'Dutch (Belgium)' },
  { code: 'pl', name: 'Polish' },
  { code: 'pt_BR', name: 'Portuguese (Brazil)' },
  { code: 'pt_PT', name: 'Portuguese (Portugal)' },
  { code: 'ro', name: 'Romanian' },
  { code: 'ro_MD', name: 'Romanian (Moldova)' },
  { code: 'ru', name: 'Russian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sr_RS_latin', name: 'Serbian (Serbia, Latin)' }, 
  { code: 'sv', name: 'Swedish' },
  { code: 'th', name: 'Thai' },
  { code: 'tr', name: 'Turkish' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'yo_NG', name: 'Yoruba (Nigeria)' },
  { code: 'zh_CN', name: 'Chinese (China)' },
  { code: 'zh_TW', name: 'Chinese (Taiwan)' },
  { code: 'zu_ZA', name: 'Zulu (South Africa)' }]

export const methods = ():FakerMethods => ({
  Airline: [
    "aircraftType",
    "airline",
    "airplane",
    "airport",
    "flightNumber",
    "recordLocator",
    "seat"
  ],
  Animal: [
    "bear",
    "bird",
    "cat",
    "cetacean",
    "cow",
    "crocodilia",
    "dog",
    "fish",
    "horse",
    "insect",
    "lion",
    "rabbit",
    "rodent",
    "snake",
    "type"
  ],
  Color: [
    "cmyk",
    "colorByCSSColorSpace",
    "cssSupportedFunction",
    "cssSupportedSpace",
    "hsl",
    "human",
    "hwb",
    "lab",
    "lch",
    "rgb",
    "space"
  ],
  Commerce: [
    "department",
    "isbn",
    "price",
    "product",
    "productAdjective",
    "productDescription",
    "productMaterial",
    "productName"
  ],
  Company: [
    "buzzAdjective",
    "buzzNoun",
    "buzzPhrase",
    "buzzVerb",
    "catchPhrase",
    "catchPhraseAdjective",
    "catchPhraseDescriptor",
    "catchPhraseNoun",
    "name",
  ],
  Database: [
    "collation",
    "column",
    "engine",
    "mongodbObjectId",
    "type"
  ],
  Datatype: [
    "boolean",
  ],
  Date: [
    "anytime",
    "birthdate",
    "future",
    "month",
    "past",
    "recent",
    "soon",
    "weekday"
  ],
  Finance: [
    "accountName",
    "accountNumber",
    "amount",
    "bic",
    "bitcoinAddress",
    "creditCardCVV",
    "creditCardIssuer",
    "creditCardNumber",
    "currency",
    "currencyCode",
    "currencyName",
    "currencySymbol",
    "ethereumAddress",
    "iban",
    "litecoinAddress",
    "maskedNumber",
    "pin",
    "routingNumber",
    "transactionDescription",
    "transactionType"
  ],
  Git: [
    "branch",
    "commitDate",
    "commitEntry",
    "commitMessage",
    "commitSha",
  ],
  Hacker: [
    "abbreviation",
    "adjective",
    "ingverb",
    "noun",
    "phrase",
    "verb"
  ],
  // Helpers: [
  //   "enumValue",
  //   "fake",
  //   "fromRegExp",
  //   "maybe",
  //   "multiple",
  //   "mustache",
  //   "objectEntry",
  //   "objectKey",
  //   "objectValue",
  //   "rangeToNumber",
  //   "regexpStyleStringParse",
  //   "replaceCreditCardSymbols",
  //   "replaceSymbolWithNumber",
  //   "replaceSymbols",
  //   "shuffle",
  //   "slugify",
  //   "unique",
  //   "uniqueArray",
  //   "weightedArrayElement",
  // ],
  Image: [
    "avatar",
    "avatarGitHub",
    "avatarLegacy",
    "dataUri",
    "url",
    "urlLoremFlickr",
    "urlPicsumPhotos",
    "urlPlaceholder"
  ],
  Internet: [
    "avatar",
    "color",
    "displayName",
    "domainName",
    "domainSuffix",
    "domainWord",
    "email",
    "emoji",
    "exampleEmail",
    "httpMethod",
    "httpStatusCode",
    "ip",
    "ipv4",
    "ipv6",
    "mac",
    "password",
    "port",
    "protocol",
    "url",
    "userAgent",
    "userName"
  ],
  Location: [
    "buildingNumber",
    "cardinalDirection",
    "city",
    "country",
    "countryCode",
    "county",
    "direction",
    "latitude",
    "longitude",
    "nearbyGPSCoordinate",
    "ordinalDirection",
    "secondaryAddress",
    "state",
    "street",
    "streetAddress",
    "timeZone",
    "zipCode",
  ],
  Lorem: [
    "lines",
    "paragraph",
    "paragraphs",
    "sentence",
    "sentences",
    "slug",
    "text",
    "word",
    "words"
  ],
  Music: [
    "genre",
    "songName"
  ],
  Number: [
    // "bigInt",
    "binary",
    "float",
    "hex",
    "int",
    "octal"
  ],
  Person: [
    "bio",
    "firstName",
    "fullName",
    "gender",
    "jobArea",
    "jobDescriptor",
    "jobTitle",
    "jobType",
    "lastName",
    "middleName",
    "prefix",
    "sex",
    "sexType",
    "suffix",
    "zodiacSign"
  ],
  Phone: [
    "imei",
    "number"
  ],
  Science: [
    "chemicalElement",
    "unit"
  ],
  String: [
    "alpha",
    "alphanumeric",
    "binary",
    // "fromCharacters",
    "hexadecimal",
    "nanoid",
    "numeric",
    "octal",
    "sample",
    "symbol",
    "uuid"
  ],
  System: [
    "commonFileExt",
    "commonFileName",
    "commonFileType",
    "cron",
    "directoryPath",
    "fileExt",
    "fileName",
    "filePath",
    "fileType",
    "mimeType",
    "networkInterface",
    "semver"
  ],
  Vehicle: [
    "bicycle",
    "color",
    "fuel",
    "manufacturer",
    "model",
    "type",
    "vehicle",
    "vin",
    "vrm"
  ],
  Word: [
    "adjective",
    "adverb",
    "conjunction",
    "interjection",
    "noun",
    "preposition",
    "sample",
    "verb",
    "words"
  ]
})
